set guifont=Monospace\ 14
" Windows alternative
" set guifont=Consolas:h12
nnoremap <M-Space> :simalt ~<CR>
set visualbell t_vb=
set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=L
