# This file contains aliases that I find convenient
# Place the contents of this file into ~/.bash_aliases

# List screens
alias sls="screen -list"

# For when I'm going to fast for my own good
alias sl="ls"
alias claer="clear"
alias celar="clear"

# Get ranked top used commands
alias topcmd="history | awk '\
  { CMD[\$2]++; count++; } \
  END{ for (c in CMD) \
    print CMD[c] \" \" CMD[c] / count * 100 \"% \" c \
  }' | column -c3 -t | sort -nr | nl"
