# This file contains aliases that I find convenient
# Place the contents of this file into ~/.bash_aliases

# List screens
alias sls="screen -list"

# For when I'm going too fast for my own good
alias sl="ls"
alias claer="clear"
alias celar="clear"

# Get ranked top used commands
alias topcmd="history | awk '\
  { CMD[\$2]++; count++; } \
  END{ for (c in CMD) \
    print CMD[c] \" \" CMD[c] / count * 100 \"% \" c \
  }' | column -c3 -t | sort -nr | nl"
#
# Nicer df output (especially when using snaps)
alias df="df -x tmpfs -x squashfs"

### Cygwin Specific ###
alias home="cd /cygdrive/c/PATH_TO_YOUR_USER"
# Note the use of the icon (optional)
alias term="cygstart mintty -i /Terminal.ico -t Cygwin /bin/bash -li"
### end Cygwin specific ###
